# build environment
FROM node as build

ARG REACT_APP_REAZO_AGENT_REAZO_IS_EVAL
ENV REACT_APP_REAZO_AGENT_REAZO_IS_EVAL $REACT_APP_REAZO_AGENT_REAZO_IS_EVAL

ARG REACT_APP_REAZO_AGENT_REAZO_API_URL
ENV REACT_APP_REAZO_AGENT_REAZO_API_URL $REACT_APP_REAZO_AGENT_REAZO_API_URL

ARG REACT_APP_REAZO_AGENT_OKTA_ISSUER
ENV REACT_APP_REAZO_AGENT_OKTA_ISSUER $REACT_APP_REAZO_AGENT_OKTA_ISSUER

ARG REACT_APP_REAZO_AGENT_OKTA_URL
ENV REACT_APP_REAZO_AGENT_OKTA_URL $REACT_APP_REAZO_AGENT_OKTA_URL

ARG REACT_APP_REAZO_AGENT_OKTA_BASE_URI
ENV REACT_APP_REAZO_AGENT_OKTA_BASE_URI $REACT_APP_REAZO_AGENT_OKTA_BASE_URI

ARG REACT_APP_REAZO_AGENT_OKTA_REDIRECT_URI
ENV REACT_APP_REAZO_AGENT_OKTA_REDIRECT_URI $REACT_APP_REAZO_AGENT_OKTA_REDIRECT_URI

ARG REACT_APP_REAZO_AGENT_OKTA_CLIENT_ID
ENV REACT_APP_REAZO_AGENT_OKTA_CLIENT_ID $REACT_APP_REAZO_AGENT_OKTA_CLIENT_ID

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install
COPY . /app
RUN npm run build

# production environment
FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx
RUN mkdir /etc/nginx/ssl
COPY ./reazo-combined-certificate.crt /etc/nginx/ssl
COPY ./reazo-san-certificate-private.key /etc/nginx/ssl
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]

